import { Resource } from "@/types";

export const mockResources: Resource[] = [
  {
    id: '1',
    title: "JavaScript Asoslari.pdf",
    type: 'pdf',
    url: '#',
    uploadedAt: new Date('2024-01-15'),
    size: '2.4 MB',
    aiTopics: ['JavaScript', 'Variables', 'Data Types'],
    courseId: '1',
    category: 'Dasturlash',
  },
  {
    id: '2',
    title: "React Hooks Qo'llanma.docx",
    type: 'docx',
    url: '#',
    uploadedAt: new Date('2024-01-20'),
    size: '1.8 MB',
    aiTopics: ['React', 'Hooks', 'useState', 'useEffect'],
    courseId: '1',
    category: 'Web Development',
  },
  {
    id: '3',
    title: "Backend Arxitekturasi.video",
    type: 'video',
    url: '#',
    uploadedAt: new Date('2024-01-25'),
    size: '450 MB',
    aiTopics: ['Backend', 'Architecture', 'Microservices'],
    courseId: '5',
    category: 'Backend',
  },
  {
    id: '4',
    title: "UI/UX Dizayn Tamoyillari.pptx",
    type: 'pptx',
    url: '#',
    uploadedAt: new Date('2024-01-28'),
    size: '12.5 MB',
    aiTopics: ['UI/UX', 'Design', 'User Interface'],
    courseId: '2',
    category: 'Dizayn',
  },
  {
    id: '5',
    title: "Database Indexing.pdf",
    type: 'pdf',
    url: '#',
    uploadedAt: new Date('2024-02-01'),
    size: '3.1 MB',
    aiTopics: ['Database', 'Indexing', 'Performance'],
    courseId: '7',
    category: 'Database',
  },
];

export const resourceCategories = [
  "Dasturlash",
  "Web Development",
  "Backend",
  "Dizayn",
  "Database",
  "AI/ML",
  "Marketing",
];
